# Generated by Django 3.0.6 on 2020-06-01 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.CharField(default='Body', max_length=2048),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 22, 13, 4, 244497), verbose_name='date created'),
        ),
    ]
